# Auxilliary

In [340]:
import os
from exp import runNSave, get_times_file, record_eye, record_fun3

# Config

In [341]:
path = "."
rules_file = os.path.join(path, "red", "rules_red0.n3")
data_file = os.path.join(path, "red", "data", "gen100_pt1.n3")

nr_runs = 5

# eye

In [342]:
times_fh = get_times_file(os.path.join(path, "red", "results"), 'eye')

query_file = os.path.join(path, "query_eye.n3")
eye_res_file = os.path.join(path, "red", "results", "eye.n3")

for run in range(0, nr_runs):
    print("run:", run)
    
    rules_name = os.path.basename(rules_file)
    data_name = os.path.basename(data_file)
    
    netw_time, reas_time = runNSave(["eye", rules_file, data_file , "--query", query_file, "--nope"], eye_res_file)
    record_eye(times_fh, run, rules_name, data_name, netw_time, reas_time)

    times_fh.flush()
    
times_fh.close()

run: 0
run: 1
run: 2
run: 3
run: 4

# fun3

In [343]:
from pathlib import Path
import sys
sys.path.insert(0, "../../")
from n3.to_py import run_py, save_py

In [344]:
times_fh = get_times_file(os.path.join(path, "red", "results"), 'fun3')

query_file = os.path.join(path, "query.n3")
code_file = os.path.join(path, "red", "results", "code_out.py")
fun3_res_file = os.path.join(path, "red", "results", "fun3.n3")

for run in range(0, nr_runs):
    print("run:", run)
    
    # save_py(Path(query_file), Path(rules_file), Path(data_file), code_file, print_code=False, add_tracing=False, code_dir="../../../..")
    
    netw_time, gen_time, exec_time, reas_time = run_py(Path(query_file), Path(rules_file), Path(data_file), save_to=fun3_res_file)
    record_fun3(times_fh, run, rules_name, data_name, netw_time, reas_time, gen_time, exec_time)
    
    times_fh.flush()
    
times_fh.close()

run: 0
run: 1
run: 2
run: 3
run: 4

# compare output

In [345]:
import sys
sys.path.insert(0, "../../")

from n3.parse import parse_n3_file

model1 = parse_n3_file(eye_res_file).data; label1 = "eye"
model2 = parse_n3_file(fun3_res_file).data; label2 = "fun3"

compliant = True
for t in model1.triples():
    if t not in model2.triples():
        print(f"different in {label1}:")
        print(t)
        compliant = False
        
for t in model2.triples():
    if t not in model1.triples():
        print(f"different in {label2}:")
        print(t)
        compliant = False
            
if compliant:
    print("compliant")
else:
    print("non compliant")

compliant

# analyze

In [346]:
from exp import load_n3_agg

In [360]:
df = load_n3_agg(os.path.join(path, "red", "results", "times_eye.csv"), "pt1")
df

,query,data,netw_time,reas_time,total_time,query_id,data_id
1,rules_red0.n3,gen100_pt1.n3,73.2,0.0,73.2,0,100
2,rules_red0.n3,gen200_pt1.n3,146.6,0.0,146.6,0,200
3,rules_red0.n3,gen500_pt1.n3,368.4,1.0,369.4,0,500
4,rules_red0.n3,gen700_pt1.n3,498.4,2.0,500.4,0,700
0,rules_red0.n3,gen1000_pt1.n3,735.0,3.2,738.2,0,1000
6,rules_red1.n3,gen100_pt1.n3,78.8,0.0,78.8,1,100
7,rules_red1.n3,gen200_pt1.n3,150.8,0.0,150.8,1,200
8,rules_red1.n3,gen500_pt1.n3,372.8,0.0,372.8,1,500
9,rules_red1.n3,gen700_pt1.n3,503.0,1.0,504.0,1,700
5,rules_red1.n3,gen1000_pt1.n3,727.2,1.0,728.2,1,1000

In [361]:
df = load_n3_agg(os.path.join(path, "red", "results", "times_fun3.csv"), "pt1")
df

,query,data,netw_time,reas_time,total_time,query_id,data_id
1,rules_red0.n3,gen100_pt1.n3,4.6,151.8,156.4,0,100
2,rules_red0.n3,gen200_pt1.n3,4.4,298.0,302.4,0,200
3,rules_red0.n3,gen500_pt1.n3,4.2,740.0,744.2,0,500
4,rules_red0.n3,gen700_pt1.n3,4.2,1024.6,1028.8,0,700
0,rules_red0.n3,gen1000_pt1.n3,4.8,1530.4,1535.2,0,1000
6,rules_red1.n3,gen100_pt1.n3,72.6,508.2,580.8,1,100
7,rules_red1.n3,gen200_pt1.n3,75.4,1048.6,1124.0,1,200
8,rules_red1.n3,gen500_pt1.n3,74.4,2525.4,2599.8,1,500
9,rules_red1.n3,gen700_pt1.n3,71.8,3539.2,3611.0,1,700
5,rules_red1.n3,gen1000_pt1.n3,72.2,5252.2,5324.4,1,1000

In [363]:
df = load_n3_agg(os.path.join(path, "red", "results", "times_fun3.csv"), "pt2")
df

,query,data,netw_time,reas_time,total_time,query_id,data_id
1,rules_red0.n3,gen100_pt2.n3,4.4,292.8,297.2,0,100
2,rules_red0.n3,gen200_pt2.n3,4.2,571.0,575.2,0,200
3,rules_red0.n3,gen500_pt2.n3,5.0,1233.4,1238.4,0,500
4,rules_red0.n3,gen700_pt2.n3,4.6,1985.2,1989.8,0,700
0,rules_red0.n3,gen1000_pt2.n3,4.2,2885.0,2889.2,0,1000
6,rules_red1.n3,gen100_pt2.n3,131.2,950.2,1081.4,1,100
7,rules_red1.n3,gen200_pt2.n3,73.4,1842.2,1915.6,1,200
8,rules_red1.n3,gen500_pt2.n3,71.4,4299.6,4371.0,1,500
9,rules_red1.n3,gen700_pt2.n3,71.6,6743.6,6815.2,1,700
5,rules_red1.n3,gen1000_pt2.n3,75.8,9758.6,9834.4,1,1000